backend:
  database:
    url: postgresql://myuser:mypassword@localhost/workoutbuddy
  ml:
    model_path: ./backend/app/models/model.pt
  app:
    secret_key: your-secret-key
    api_host: 127.0.0.1
    api_port: 8000
  logging:
    level: INFO
frontend:
  api_base_url: http://127.0.0.1:8000
  environment: development
  feature_flags:
    enable_social: true
    enable_ai: true 