# WorkoutBuddy Backend Configuration
# ==================================
#
# This YAML file contains all configuration settings for the WorkoutBuddy
# AI-powered fitness platform backend. It provides a centralized location
# for managing application behavior, ML hyperparameters, and service settings.
#
# Configuration Sections:
# - database: PostgreSQL connection for production data
# - app: FastAPI server settings
# - logging: Application-wide logging configuration
# - ai: Anthropic Claude integration and ML hyperparameters
# - analytics: PostHog analytics and user tracking
# - ab_testing: Experiment framework for feature validation
# - ml: Machine learning algorithms and hyperparameters
#
# Environment Variables (API keys are always loaded from environment):
# - ANTHROPIC_API_KEY: Anthropic API authentication key
# - POSTHOG_API_KEY: PostHog project API key for analytics
# - DATABASE_URL: PostgreSQL connection string (overrides YAML if set)
# - SECRET_KEY: Application secret for JWT signing (overrides YAML if set)
# - LOG_LEVEL: Python logging level (DEBUG, INFO, WARNING, ERROR)
# - API_HOST: Server host interface (default: 0.0.0.0)
# - API_PORT: Server port number (default: 8000)
#
# Hyperparameter Tuning:
# All ML model settings can be adjusted here without code changes:
# - Feature weights for community matching
# - AI model temperature and creativity
# - Similarity algorithm selection
# - A/B testing parameters
#
# Usage:
# This file is automatically loaded by the backend when starting.
# Changes take effect after restarting the application.
# API keys are always loaded from environment variables for security.

backend:
  database:
    url: "postgresql://wojciechkowalinski@localhost/workoutbuddy"
  
  app:
    secret_key: "dev-secret-key-change-in-production"
    api_host: "0.0.0.0"
    api_port: 8000
  
  logging:
    level: "INFO"
  
  ai:
    # AI Service Configuration (Anthropic Claude)
    # API key is always loaded from ANTHROPIC_API_KEY environment variable
    enabled: true                              # Automatically enabled if ANTHROPIC_API_KEY is set
    model_name: "claude-3-haiku-20240307"     # Claude model for AI features
    max_tokens: 500                           # Maximum response length
    temperature: 0.7                          # Creativity level (0.0-1.0)
    # Challenge Generation Hyperparameters
    challenge_creativity: 0.8                 # How creative challenges should be
    challenge_difficulty_range: [1, 5]        # Min/max difficulty levels
    # Community Matching Parameters
    compatibility_threshold: 0.7              # Minimum match score
    max_matches: 10                           # Maximum matches to return
    # Encouragement Generation
    encouragement_tone_variety: 0.6           # Message tone variation
    personalization_weight: 0.8               # Personalization level
  
  analytics:
    # PostHog API key is always loaded from POSTHOG_API_KEY environment variable
    posthog_host: "https://app.posthog.com"
    # Event Tracking Configuration
    batch_size: 100
    flush_interval: 30  # seconds
    max_retries: 3
  
  ab_testing:
    enabled: true
    # Experiment Configuration
    default_traffic_allocation: 0.5
    minimum_sample_size: 100
    confidence_level: 0.95
    # Hash Configuration for User Assignment
    hash_seed: "workoutbuddy-experiments"
    # Active Experiments
    active_experiments:
      - "ai_challenges_v1"
      - "ai_community_matching_v1"
      - "encouragement_frequency_v1"
  
  ml:
    # Community Matching ML Parameters
    similarity_algorithm: "cosine"  # cosine, jaccard, euclidean
    feature_weights:
      goal_type: 0.3
      activity_level: 0.2
      schedule_compatibility: 0.2
      engagement_score: 0.15
      location_proximity: 0.15
    # Recommendation Engine
    recommendation_model: "collaborative_filtering"
    n_recommendations: 5
    min_user_interactions: 5
    # Cohort Analysis
    cohort_window_days: 30
    retention_analysis_periods: [7, 14, 30, 90]
    # Anomaly Detection
    anomaly_threshold: 2.0  # Standard deviations
    min_data_points: 10 