# Base Configuration for Pulse Fitness
# This file contains default configuration values

# Application Settings
app:
  name: "Pulse Fitness"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8000
  debug: false

# Database Configuration
database:
  url: "sqlite:///./pulse_fitness.db"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo: false
  migration_auto: true

# Redis Configuration
redis:
  url: "redis://localhost:6379/0"
  host: "localhost"
  port: 6379
  db: 0
  password: null
  ssl: false
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5

# Security Configuration
security:
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  password_min_length: 8
  password_require_special: true
  password_require_numbers: true
  password_require_uppercase: true
  rate_limit_requests: 100
  rate_limit_window: 3600
  cors_origins: ["*"]
  cors_allow_credentials: true

# Machine Learning Configuration
ml:
  vector_db_url: null
  model_cache_dir: "./models"
  embedding_dimensions: 1536
  similarity_threshold: 0.7
  max_recommendations: 10
  batch_size: 32

# External Services Configuration
external:
  email_service_url: null
  push_notification_url: null
  file_storage_url: null
  sms_service_url: null

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: null
  max_file_size: 10485760  # 10MB
  backup_count: 5
  enable_console: true
  enable_file: false

# Monitoring Configuration
monitoring:
  enable_health_checks: true
  enable_metrics: true
  enable_tracing: false
  metrics_port: 9090
  health_check_interval: 30
  performance_monitoring: true

# Feature Flags
features:
  enable_ml_recommendations: true
  enable_social_features: true
  enable_safety_moderation: true
  enable_push_notifications: true
  enable_email_notifications: true
  enable_file_upload: true
  enable_analytics: true
  enable_debug_mode: false 