database:
  url: postgresql://myuser:mypassword@localhost/workoutbuddy
ml:
  model_path: ./models/model.pt
app:
  secret_key: your-secret-key
  api_host: 127.0.0.1
  api_port: 8000
logging:
  level: INFO 