"""add personalized_message to friend_invitations

Revision ID: a7a30d6b7e5d
Revises: 1e63cee4a874
Create Date: 2025-06-29 12:31:21.078598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a30d6b7e5d'
down_revision: Union[str, None] = '1e63cee4a874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_invitations', sa.Column('personalized_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend_invitations', 'personalized_message')
    # ### end Alembic commands ###
