"""add invitee_phone to friend_invitations and make invitee_email nullable

Revision ID: d801a7adea45
Revises: a7a30d6b7e5d
Create Date: 2025-06-29 12:36:57.535225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd801a7adea45'
down_revision: Union[str, None] = 'a7a30d6b7e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_invitations', sa.Column('invitee_phone', sa.String(), nullable=True))
    op.alter_column('friend_invitations', 'invitee_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friend_invitations', 'invitee_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('friend_invitations', 'invitee_phone')
    # ### end Alembic commands ###
