# docker-compose.yml (root level)
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pulse-db
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse123
      POSTGRES_DB: pulse_fitness
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pulse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pulse-backend
    environment:
      DATABASE_URL: postgresql://pulse:pulse123@db:5432/pulse_fitness
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY:-your-secret-key}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      DATA_PATH: /app/data
      ML_MODEL_PATH: /app/ml_models
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ml_models:/app/ml_models
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: pulse-mobile
    volumes:
      - ./mobile:/app
    ports:
      - "8080:8080"
    environment:
      API_BASE_URL: http://backend:8000
    command: flutter run -d web-server --web-hostname 0.0.0.0 --web-port 8080

volumes:
  postgres_data:
  redis_data:
  ml_models: